server:
  port: 8006

spring:
  application:
    name: user-service


  datasource:
    url: jdbc:mysql://localhost:3306/architecture_db
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/