server:
  port: 8904

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置存储配置信息的Git仓库
          # 配置存储配置信息的Git仓库 http://localhost:8901/master/config-dev.yml
          uri: https://gitee.com/chaomian93/architecture-config
          # 开启启动时直接从git获取配置
          clone-on-start: true
          # 获取子目录下的配置
    #          search-paths: '{application}'
  # rabbitmq相干配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
